classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.mbari_wec.readers.MbariWecDataReader

  # .*:
  #   classname: tsdat.io.readers.CSVReader
  #   parameters: # Parameters to pass to CsvHandler. Comment out if not using.
  #     read_csv_kwargs:
  #       sep: ", *"
  #       engine: "python"
  #       index_col: False

coords:
  # DEVELOPER: Specify the coords/data_vars that should be retrieved from any inputs
  time:
    # Mapping of regex pattern (matching input key/file) to input name & converter(s) to
    # run. The default is .*, which matches everything. Put the most specific patterns
    # first because searching happens top -> down and stops at the first match.
    .*:
      # The name of the input variable as returned by the selected reader. If using a
      # built-in DataReader like the CSVReader or NetCDFReader, then will be exactly the
      # same as the name of the variable in the input file.
      name: time

  freq:
    .*:
      name: freq

data_vars:
  batter_voltage:
    .*:
      name: batter_voltage
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: V

  battery_power:
    .*:
      name: battery_power
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: W

  wave_dir:
    .*:
      name: wave_dir
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: deg
