attrs:
  title: NCEI Arctic Cruise Example
  description:
    Historial marine data that are comprised of ship, buoy and platform observations.
  location_id: arctic_ocean
  dataset_name: ncei_arctic_cruise_example
  data_level: a1
  # qualifier:
  # temporal:
  # institution:

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00

data_vars:
  latitude: # Name of variable in retriever.yaml
    dims: [time] # Variable dimension(s), separated by ","
    dtype: float # Datatype
    attrs:
      long_name: Latitude # Name used in plotting
      units: deg N # Units, necessary for unit conversion
      comment: "" # Add a comment or description if necessary
      _FillValue: 99 # Bad data marker in raw dataset, otherwise -9999
      fail_range: [-90, 90] # Expected failure range for "CheckFailMax"/Min" QC tests

  longitude:
    dims: [time]
    dtype: float
    attrs:
      long_name: Latitude
      units: deg N
      comment: ""

  pressure:
    dims: [time]
    dtype: float
    attrs:
      long_name: Pressure at Sea Level
      units: dbar
      comment: ""

  temperature:
    dims: [time]
    dtype: float
    attrs:
      long_name: Air Temperature
      units: degC
      comment: ""

  dew_point:
    dims: [time]
    dtype: float
    attrs:
      long_name: Dew Point
      units: degC
      comment: ""

  wave_period:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wave Period
      units: s
      comment: Assumed to refer to average wave period
      _FillValue: 99
      warn_range: [0, 22] # Expected range for "CheckWarnMax"/Min" QC tests

  wave_height:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wave Height
      units: m
      comment: Assumed to refer to average wave height

  swell_direction:
    dims: [time]
    dtype: float
    attrs:
      long_name: Swell Direction
      units: deg from N
      comment: Assumed to refer to peak wave direction
      fail_range: [0, 360]

  swell_period:
    dims: [time]
    dtype: float
    attrs:
      long_name: Swell Period
      units: s
      comment: Assumed to refer to peak wave period
      warn_range: [0, 22]

  swell_height:
    dims: [time]
    dtype: float
    attrs:
      long_name: Swell Height
      units: m
      comment: Assumed to refer to significant wave height

  wind_direction:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wind Direction
      units: deg from N
      comment: ""
      fail_range: [0, 360]

  wind_speed:
    dims: [time]
    dtype: float
    attrs:
      long_name: Wind Speed
      units: m/s
      comment: ""
