classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: tsdat.io.readers.CSVReader
    parameters: # Parameters to pass to CsvHandler. Comment out if not using.
      read_csv_kwargs:
        sep: ", *"
        engine: "python"
        index_col: False

coords:
  time:
    # Mapping of regex pattern (matching input key/file) to input name & converter(s) to
    # run. The default is .*, which matches everything. Put the most specific patterns
    # first because searching happens top -> down and stops at the first match.
    .*:
      # The name of the input variable as returned by the selected reader. If using a
      # built-in DataReader like the CSVReader or NetCDFReader, then will be exactly the
      # same as the name of the variable in the input file.
      name: Time of Observation

      # Optionally specify converters to run. The one below converts string values into
      # datetime64 objects. It requests two arguments: format and timezone. Format is
      # the string time format of the input data (see strftime.org for more info), and
      # timezone is the timezone of the input measurement.
      data_converters:
        - classname: tsdat.io.converters.StringToDatetime
          format: "%Y-%m-%dT%H:%M:%S"
          timezone: UTC

data_vars:
  latitude:
    .*:
      name: Latitude

  longitude:
    .*:
      name: Longitude

  pressure:
    .*:
      name: Sea Level Pressure
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: hPa

  temperature:
    .*:
      name: Air Temperature
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: degF

  dew_point:
    .*:
      name: Dew Point Temperature
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: degF

  wave_period:
    .*:
      name: Wave Period

  wave_height:
    .*:
      name: Wave Height
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: ft

  swell_direction:
    .*:
      name: Swell Direction

  swell_period:
    .*:
      name: Swell Period

  swell_height:
    .*:
      name: Swell Height
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: ft

  wind_direction:
    .*:
      name: Wind Direction

  wind_speed:
    .*:
      name: Wind Speed
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: dm/s
