classname: pipelines.example_pipeline.pipeline.ExamplePipeline

triggers:
  - .*example_pipeline.*\.csv

retriever:
  path: pipelines/example_pipeline/config/retriever.yaml

dataset:
  path: pipelines/example_pipeline/config/dataset.yaml

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
